rudderlabs/rudder-sdk-react-native

Example/App.js
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java

Handled the case in which there were no factories while initializing the SDK , after adding the support for checking if an integration is ready
> Fix [#1]()

Handled Initialization of SDK with No Factories 

---

package.json
yarn.lock

When running a type check with this package installed, it throws type errors since the TS source isnt built to CommonJS. I temporarily fixed the type error, but the package should be distributed with commonJS.
Example of build set up for commonJS: https://github.com/callstack/react-native-builder-bob
Quick workaround for https://github.com/rudderlabs/rudder-sdk-react-native/issues/74

Add @types/async-lock to resolve missing module typecheck

---

.nxignore

exclude package json from nx affected packages resolution
> https://www.notion.so/rudderstacks/React-Native-deploy-action-to-not-attempt-to-publish-non-affected-packages-and-auto-trigger-on-the-c-e8f95275336e4bdc97895299c22b9977?pvs=4

ci(rudder-sdk-react-native-monorepo): exclude package json from nx affected packages resolution

---

CODEOWNERS
apps/example/ios/Podfile
apps/example/ios/Podfile.lock
libs/rudder-integration-firebase-react-native/android/build.gradle
libs/rudder-integration-firebase-react-native/rudder-integration-firebase-react-native.podspec
package-lock.json

- Updated the sample app to enable the modular dependency of Firebase pods which resolves the latest Rudder-Firebase iOS installation issue.
- Updated the Firebase minimum version to the latest.
- Updated the codeowner.
> Fix [#1]()

fix: update the minimum version in the rn firebase

---

apps/example/ios/Podfile.lock
libs/sdk/ios/RNParamsConfigurator.h
libs/sdk/ios/RNRudderSdkModule.m
libs/sdk/ios/RNUserSessionPlugin.h
package-lock.json

- Rudder-iOS SDK version 1.19.0 caused this compilation issue on the iOS build.
- To fix that we are now importing the required file directly into the iOS module.
- https://github.com/rudderlabs/rudder-sdk-react-native/issues/231

fix: ios module compilation error

---

apps/example/ios/Example.xcodeproj/project.pbxproj
apps/example/ios/Podfile
apps/example/ios/Podfile.lock
libs/sdk/RNRudderSdk.podspec
libs/sdk/ios/RNParamsConfigurator.m

- Bump the iOS SDK minimum version to `1.20.0` to resolve the Invalid JSON issue and Sqlite issue.
- Comment out the DBEncryption code (it'll be implemented in future).
- Update Sample iOS app Podfile to make the build compatible with the latest version of iOS SDK i.e., 1.20.0.
- https://github.com/rudderlabs/rudder-sdk-react-native/issues/243
- https://github.com/rudderlabs/rudder-sdk-react-native/issues/245

fix: iOS build issue

---

libs/sdk/android/src/main/java/com/rudderstack/react/android/LifeCycleEvents.java
libs/sdk/android/src/main/java/com/rudderstack/react/android/RNLifeCycleEventListener.java
libs/sdk/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
libs/sdk/ios/RNRudderSdkModule.m

- Fixes the issue when `live reload` occurs (it can be done by pressing `r` in the simulator, or due to some other factors when `fast refresh` occurs): Now, whenever live reload occurs, the Rudder React Native SDK will need to be explicitly initialized before it starts functioning.
- In React Native iOS, this was a major issue, visible clearly, which is fixed.
- In React Native Android, this was mainly affecting the LifeCycle events, which is fixed.
> Fix [#1]()

fix: issue with the live reload

---

apps/example/ios/Podfile.lock
apps/example/src/app/RudderEvents.tsx
libs/sdk/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
libs/sdk/src/IRudderContext.ts
libs/sdk/src/NativeBridge.ts
libs/sdk/src/RudderClient.ts
libs/sdk/src/RudderContext.ts
libs/sdk/src/index.ts
package-lock.json

- Added the `IRudderContext` interface in the React Native SDK, which basically defines the context fields. Now this interface is also exported.
- Change the `getRudderContext` API return type from `void` to `IRudderContext | null`.
- Updated the sample app to use this API.
- Also, added GDPR API in the sample app.
> Fix https://github.com/rudderlabs/rudder-sdk-react-native/issues/263

fix: improve getRudderContext api return type 

---

libs/plugins/rudder-plugin-db-encryption-react-native/project.json
package-lock.json

- `"releaseAs": "major"` was kept to release the `DBEncryption` plugin as `v1.0.0` and now it is no longer required. Hence reverting the change.
> Fix [#1]()

chore: remove releaseAs from dbEncryption plugin

---

apps/example/ios/Podfile.lock
libs/sdk/android/src/main/java/com/rudderstack/react/android/RNPreferenceManager.java
libs/sdk/android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
libs/sdk/android/src/main/java/com/rudderstack/react/android/Utility.java
libs/sdk/ios/RNPreferenceManager.h
libs/sdk/ios/RNPreferenceManager.m
libs/sdk/ios/RNRudderSdkModule.m

- When upgrading the React Native SDK from version `1.7.1` to `1.11.1` (the latest version as of now), the Application Installed event is mistakenly fired instead of the Application Updated event. This PR resolves this issue, ensuring that the Application Updated event is now correctly triggered during the upgrade process.
> Fix [#1]()

fix: incorrect tracking of application lifecycle events

---

apps/example/ios/Podfile.lock
libs/sdk/RNRudderSdk.podspec

:crown: *An automated PR*
> Update the minimum version of the iOS SDK in the React Native package to `1.24.1`. This will fix the compatibility issue with Bugsnag React Native SDK.

fix: compatibility issue of the rudder react native ios sdk with bugsnag

---

apps/example/ios/Podfile.lock
libs/plugins/rudder-plugin-db-encryption-react-native/rudder-plugin-db-encryption-react-native.podspec

> In the past two releases, I observed that RN CI/CD is failing due to Nx detecting changes in the `dbEncryption` plugin. These changes were made with a `chore` PR title, causing the issue. To resolve this, I attempted to update the minimum version of the iOS SDK. This will generate a new dbEncryption version, and hopefully, resolve the issue.
> Fix [#1]()

fix: update minimum version of ios sdk to 1.24.1 in dbEncryption plugin

---

apps/example/android/app/src/main/AndroidManifest.xml
package-lock.json
package.json

- Fixed the npm security issue by overriding the `git-raw-commits` to `v4.0.0`.
- There is the following build error in Android, we solved it by setting the `android:allowBackup` flag to `true` in the Android sample app. This issue seems to be caused due to some change in the AppsFlyer Android SDK AndroidManifest.xml file:
```
> Task :app:processDebugMainManifest FAILED
/Users/abhishekpandey/Documents/Abhishek/fix/Fix_iOS/rudder-sdk-react-native/apps/example/android/app/src/debug/AndroidManifest.xml:10:7-34 Error:
Attribute application@allowBackup value=(false) from AndroidManifest.xml:10:7-34
is also present at [com.appsflyer:af-android-sdk:6.14.0] AndroidManifest.xml:32:9-35 value=(true).
Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at …
```

chore: fix npm security and android build issues

---

apps/example/ios/Podfile.lock
libs/sdk/RNRudderSdk.podspec

- We have updated the minimum iOS SDK version in the React Native SDK to `v1.26.3` to address the following issue:
> We've decided to remove the tracking domain URL from the Privacy Manifest file. This change aims to resolve the error that occurs when a request to our tracking domain gets blocked after the user denies tracking permission.
Refer to this PR: https://github.com/rudderlabs/rudder-sdk-ios/pull/509.
> Fix [#1]()

fix: update the version of iOS SDK to address the Privacy Manifest issue

---

apps/example/ios/Podfile.lock
apps/example/src/app/App.tsx
apps/example/src/app/RudderEvents.tsx
libs/sdk/android/src/main/java/com/rudderstack/react/android/Utility.java
libs/sdk/ios/RNRudderSdkModule.m

- Added the functionality to set `customContext` through the options object both while initializing the SDK and when making any events, such as track.
- Here is the `options` object:
```
{
externalIds: [
{
id: '2d31d085-4d93-4126-b2b3-94e651810673',
type: 'brazeExternalId',
},
],
integrations: {
// specifying destination by its display name
Amplitude: true,
Mixpanel: false,
},
tier: {
category: 'premium',
type: 'gold',
},
account: {
level: 'standard',
membership: 'silver',
},
};
```
> Fix [#1]()

feat: provide putCustomContext API support

---

.github/workflows/build-ios-checks.yml
.github/workflows/check-compatibility-of-native-sdks.yml
libs/plugins/rudder-plugin-db-encryption-react-native/android/build.gradle
package-lock.json
package.json

- Provide support for the latest DBEncryption plugin by replacing `net.zetetic:android-database-sqlcipher` with `net.zetetic:sqlcipher-android`. Corresponding changes have already been done on the native Android side since [v1.23.0](https://github.com/rudderlabs/rudder-sdk-android/blob/develop/CHANGELOG.md#1230-2024-05-20).
- Bumped the native Android SDK to the latest version in the DBEncryption Android module.
- Set the Cocopod version to `1.15.2` in `build-ios-checks.yml` and `check-compatibility-of-native-sdks.yml`.
> Fix [#1]()

feat: use the sqlcipher-android library in db encryption android plugin

---

libs/rudder-integration-facebook-react-native/project.json

This will ensure the version bump happens based on the commit types.
It was previously set to `major` to ensure the first release happens as `v1.0.0`. Now we no longer need that.
> Fix [#1]()

fix: revert releaseAs set to major in project.json

---

apps/example/ios/Example.xcodeproj/project.pbxproj
apps/example/ios/Podfile.lock
apps/example/src/app/App.tsx
libs/sdk/android/src/main/java/com/rudderstack/react/android/RNParamsConfigurator.java
libs/sdk/ios/RNParamsConfigurator.m
libs/sdk/src/Constants.ts
libs/sdk/src/NativeBridge.ts
libs/sdk/src/RudderClient.ts
libs/sdk/src/RudderConfiguration.ts

- In this PR, we added the GZIP configuration support in React Native SDK.
- User can now enable or disbale GZIP by setting `isGzip` to true/false while SDK init:
```
const config = {
dataPlaneUrl: TEST_DATAPLANE_URL,
isGzip: false,
};
await rc.setup(TEST_WRITE_KEY, config, options);
```
- By default, GZIP will be enabled.
> Fix [#1]()

feat: add gzip configuration support

---

libs/plugins/rudder-plugin-db-encryption-react-native/src/dbEncryptionPlugin.ts

> Added a dummy commit (with no actual change). Which is required for changelog generation.
NOTE: There is a known issue with NX where, if we make a change in the RN core SDK, the DBEncryption plugin also gets affected, which in turn impacts the release pipeline.
> Fix [#1]()

fix: add dummy commit to trigger changelog generation

---

apps/example/ios/Podfile
apps/example/ios/Podfile.lock
libs/rudder-integration-braze-react-native/android/build.gradle
libs/rudder-integration-braze-react-native/rudder-integration-braze-react-native.podspec

- Braze-Android: Updated the minimum Braze Android integration to `v2.0.0`. Also removed the Braze SDK dependencies from the RN Braze integration, as that is not required.
- Braze-iOS: Updated the minimum Braze iOS integration to `v4.0`.  Also, updated the iOS deployment target to 13.0 (this is in sync with the Braze-iOS integration).
- Sample app: Removed the Braze integration from the iOS sample app.
> Fix [#1]()

feat!: update the braze integration to the latest version
