src/NativeBridge.ts
src/RudderClient.ts

Reference : [#8](https://github.com/rudderlabs/rudder-sdk-react-native/issues/8)

Enabled building with strictNullChecks

---

android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdkModule.m
src/Constants.ts
src/Logger.ts
src/NativeBridge.ts
src/RudderClient.ts
src/RudderConfiguaration.ts

Added support for device tokens

---

integrations/rudder-integration-appcenter-react-native/README.md

Updated Appcenter RN Mode Readme

---

Example/App.js
Example/__mocks__/nativebridge.js
Example/__tests__/App-test.js
Example/package.json

Fixed Unit Testcases issue

---

android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdkModule.m

Fixed Screen Missing Name issue

---

Example/App.js
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
integrations/rudder-integration-appcenter-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appcenter/RudderIntegrationAppcenterReactNativeModule.java
integrations/rudder-integration-appcenter-react-native/ios/RudderIntegrationAppcenterReactNative.m
ios/RNRudderSdkModule.m
src/NativeBridge.ts
src/RudderClient.ts

Added Opt-in, Opt-out support for Appcenter in Android

---

integrations/rudder-integration-clevertap-react-native/package.json

Updated version to 1.0.0

---

integrations/rudder-integration-appsflyer-react-native/android/build.gradle

Updated Versions for AppsFlyer

---

integrations/rudder-integration-appsflyer-react-native/package.json

Bumped Version to 1.0.3

---

android/build.gradle
integrations/rudder-integration-appcenter-react-native/android/build.gradle
integrations/rudder-integration-appsflyer-react-native/android/build.gradle
integrations/rudder-integration-clevertap-react-native/android/build.gradle
integrations/rudder-integration-firebase-react-native/android/build.gradle

Migrate RN SDK and Device Mode Integrations from Jcenter to MavenCentral

---

android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
package.json

Fixed Reinitialization in Native Android of RN SDK

---

Example/App.js
Example/ios/Podfile
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
android/src/main/java/com/rudderstack/react/android/Utility.java
ios/RNRudderSdkModule.m
package.json
src/NativeBridge.ts
src/RudderClient.ts

RudderOption Feature 

---

android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java

Fixed Extra Parameter Issue in RNRudderSDKModule.setup()

---

package.json

Bumped version to 1.0.8

---

Example/App.js
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
package.json
src/Constants.ts
src/Logger.ts
src/NativeBridge.ts
src/RudderClient.ts
src/RudderConfiguaration.ts

Handling Concurrent calls to the setup method

---

ios/RNRudderSdkModule.m
package.json
src/Constants.ts

Fixed Memory Leak initially by Limiting Setup to only once

---

package.json
src/Constants.ts

Making Standard release of 1.0.9

---

package.json
src/Constants.ts

Bumped Version to 1.0.10

---

Example/App.js
Example/ios/Podfile.lock
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdkModule.m
package.json
src/Constants.ts
src/NativeBridge.ts
src/RudderClient.ts

Migrate callback to promise

---

Example/App.js
integrations/rudder-integration-appsflyer-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appsflyer/RudderIntegrationAppsflyerReactNativeModule.java
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.h
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.m
integrations/rudder-integration-appsflyer-react-native/package.json

Added Methods for Retrieving AppsFlyerId in AppsFlyer Integration

---

Example/App.js
Example/ios/Podfile.lock
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdk.podspec
ios/RNRudderSdkModule.m
package.json
src/Constants.ts

Identify Blank UserId Fix

---

Example/android/build.gradle
README.md

Removed Bintray references from Readme and build.gradle files

---

android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdk.podspec
ios/RNRudderSdkModule.m
package.json
src/Constants.ts
src/NativeBridge.ts
src/RudderClient.ts

GDPR Support for RN SDK

---

Example/ios/Podfile.lock
android/build.gradle
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdk.podspec
ios/RNRudderSdkModule.m
package.json
src/Constants.ts

Updated SDK's versions and Added Dropping logs

---

android/build.gradle
ios/RNRudderSdk.podspec
package.json
src/Constants.ts
src/RudderClient.ts

Fixed Options Being not sent in Identify call

---

android/build.gradle
ios/RNRudderSdk.podspec
package.json

> Version updated for iOS & Android.

[Release] Version 1.0.16

---

Example/App.js
Example/ios/Example.xcodeproj/project.pbxproj
Example/ios/Podfile.lock
android/.project
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdkModule.m
package.json
src/Constants.ts
src/NativeBridge.ts
src/RudderClient.ts

Marked old api's as deprecated and added new api's for uniform naming pattern

---

integrations/rudder-integration-clevertap-react-native/android/build.gradle
integrations/rudder-integration-clevertap-react-native/package.json
integrations/rudder-integration-clevertap-react-native/rudder-integration-clevertap-react-native.podspec

Using latest Native Device modes in Clevertap RN Plugin

---

integrations/rudder-integration-appcenter-react-native/package.json
integrations/rudder-integration-firebase-react-native/package.json

Bumped versions of Appcenter, Firebase RN Device Mode Plugins

---

package.json
src/Constants.ts

Bumped version to 1.1.1

---

package.json
src/Constants.ts
yarn.lock

Moving changes from develop <-> master

---

CODEOWNERS

Merge Master -> Develop
> Fix [#1]()

Merge Master -> Develop

---

integrations/rudder-integration-firebase-react-native/android/build.gradle
integrations/rudder-integration-firebase-react-native/package.json
integrations/rudder-integration-firebase-react-native/rudder-integration-firebase-react-native.podspec

Updated Firebase RN Device Mode to point to latest Native Device Modes
[Notion Link](https://github.com/rudderlabs/rudder-sdk-react-native/pull/79#issue-1108909594) 
> Fix [#1]()

[BugFix] Updated Firebase RN Device Mode to point to latest Native Device Modes

---

integrations/rudder-integration-firebase-react-native/rudder-integration-firebase-react-native.podspec

[BugFix] Updated Firebase iOS Device Mode Version in Firebase RN Device Mode
[Notion Link](https://www.notion.so/rudderstacks/Firebase-iOS-Device-Mode-5a93825065e1404f8c40002690c7d357)

[BugFix] Updated Firebase iOS Device Mode Version in Firebase RN Device Mode

---

integrations/rudder-integration-firebase-react-native/android/build.gradle
integrations/rudder-integration-firebase-react-native/package.json

[BugFix] Updated Firebase Android Device Mode and RN Device Mode Version
[Notion Link](https://www.notion.so/rudderstacks/Firebase-iOS-Device-Mode-5a93825065e1404f8c40002690c7d357)
> Fix [#1]()

[BugFix] Updated Firebase Android Device Mode and RN Device Mode Version

---

integrations/rudder-integration-firebase-react-native/android/build.gradle
integrations/rudder-integration-firebase-react-native/package.json
integrations/rudder-integration-firebase-react-native/rudder-integration-firebase-react-native.podspec

[Release] Firebase RN Device Mode Version 1.0.7
[Notion Link](https://www.notion.so/rudderstacks/Firebase-iOS-Device-Mode-5a93825065e1404f8c40002690c7d357)

[Release] Firebase RN Device Mode Version 1.0.7

---

package.json
src/Constants.ts

Alias & Group Call Implementation

[Feature] Alias & Group Call Implementation

---

package.json
src/Constants.ts

Bumped version to 1.2.1

---

Example/App.js
Example/ios/Example.xcodeproj/project.pbxproj
Example/ios/Example/AppDelegate.m
Example/ios/Example/Images.xcassets/AppIcon.appiconset/Contents.json
Example/ios/Podfile.lock
Example/yarn.lock
integrations/rudder-integration-appsflyer-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appsflyer/RudderIntegrationAppsflyerReactNativeModule.java
integrations/rudder-integration-appsflyer-react-native/ios/AppsFlyerAttribution.h
integrations/rudder-integration-appsflyer-react-native/ios/AppsFlyerAttribution.m
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.h
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.m
integrations/rudder-integration-appsflyer-react-native/package.json
integrations/rudder-integration-appsflyer-react-native/rudder-integration-appsflyer-react-native.podspec
integrations/rudder-integration-appsflyer-react-native/src/appsflyer.js

Enhanced listeners on iOS Devices for Appsflyer Device Mode

---

RNRudderSdk.podspec
android/src/main/java/com/rudderstack/react/android/RNRudderSdkModule.java
ios/RNRudderSdkModule.m
package.json
src/Constants.ts
src/NativeBridge.ts
src/RudderClient.ts

[Release] Version 1.4.0

---

android/build.gradle
src/RudderClient.ts

Bumped android sdk version to 1.5.1

---

integrations/rudder-integration-appsflyer-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appsflyer/RudderIntegrationAppsflyerReactNativeModule.java
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.h
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.m
integrations/rudder-integration-appsflyer-react-native/package.json
integrations/rudder-integration-appsflyer-react-native/src/appsflyer.js

[Feature] Extra Api Support for Appsflyer Device Mode

---

integrations/rudder-integration-appsflyer-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appsflyer/RudderIntegrationAppsflyerReactNativeModule.java
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.h
integrations/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.m
integrations/rudder-integration-appsflyer-react-native/package.json
integrations/rudder-integration-appsflyer-react-native/src/appsflyer.js

[Release] Appsflyer RN Device Mode Version 1.3.0

---

RNRudderSdk.podspec
android/build.gradle
ios/RNRudderAnalytics.h
package.json
src/Constants.ts

Fixing the native SDK versions to patch versions

---

integrations/rudder-integration-braze-react-native/android/build.gradle
integrations/rudder-integration-braze-react-native/android/common_task.gradle
integrations/rudder-integration-braze-react-native/android/gradle/wrapper/gradle-wrapper.properties
integrations/rudder-integration-moengage-react-native/android/build.gradle
integrations/rudder-integration-moengage-react-native/android/common_task.gradle
integrations/rudder-integration-moengage-react-native/android/gradle/wrapper/gradle-wrapper.properties
integrations/rudder-integration-singular-react-native/android/build.gradle
integrations/rudder-integration-singular-react-native/android/common_task.gradle
integrations/rudder-integration-singular-react-native/android/gradle/wrapper/gradle-wrapper.properties

> Fixed gradle build issue on Braze, MoEngage and Singular.
> Fix [#1]()

Fixed Gradle issue for Android device mode: Braze, MoEngage, Singular

---

integrations/rudder-integration-braze-react-native/android/build.gradle
integrations/rudder-integration-braze-react-native/android/common_task.gradle
integrations/rudder-integration-braze-react-native/android/gradle/wrapper/gradle-wrapper.properties
integrations/rudder-integration-braze-react-native/package.json
integrations/rudder-integration-moengage-react-native/android/build.gradle
integrations/rudder-integration-moengage-react-native/android/common_task.gradle
integrations/rudder-integration-moengage-react-native/android/gradle/wrapper/gradle-wrapper.properties
integrations/rudder-integration-moengage-react-native/package.json
integrations/rudder-integration-singular-react-native/android/build.gradle
integrations/rudder-integration-singular-react-native/android/common_task.gradle
integrations/rudder-integration-singular-react-native/android/gradle/wrapper/gradle-wrapper.properties
integrations/rudder-integration-singular-react-native/package.json

> Updated package.json file for MoEngage, Braze and Singular.
> Fix [#1]()

Updated package.json file for RN integrations

---

integrations/rudder-integration-appcenter-react-native/package.json
integrations/rudder-integration-clevertap-react-native/package.json
integrations/rudder-integration-firebase-react-native/package.json

Updated version in package.json file for AppCenter, CleverTap & Firebase

---

package.json

> Upgrade version of Core SDK to 1.5.0

Upgrade version of Core SDK to 1.5.0

---

src/Constants.ts

Update Version in Constants

---

package.json
src/Constants.ts

> Updated Version in Constants.ts

Updated Version in Constants.ts

---

integrations/rudder-integration-braze-react-native/android/build.gradle
integrations/rudder-integration-braze-react-native/package.json

> Updated the default version in Braze Android to 1.0.7.
> Fix [#1]()

Updated the default version in Braze Android

---

.github/workflows/build-and-quality-checks.yml
.github/workflows/build-android-checks.yml
.github/workflows/build-ios-checks.yml
github-release.config.js
libs/rudder-integration-amplitude-react-native/project.json
libs/rudder-integration-appcenter-react-native/project.json
libs/rudder-integration-appsflyer-react-native/project.json
libs/rudder-integration-braze-react-native/project.json
libs/rudder-integration-clevertap-react-native/project.json
libs/rudder-integration-firebase-react-native/project.json
libs/rudder-integration-moengage-react-native/project.json
libs/rudder-integration-singular-react-native/project.json
libs/sdk/README.md
libs/sdk/project.json
package.json

fix: add .plist file and enhance build and quality check action

---

libs/rudder-integration-amplitude-react-native/project.json
libs/rudder-integration-appcenter-react-native/project.json
libs/rudder-integration-appsflyer-react-native/project.json
libs/rudder-integration-braze-react-native/project.json
libs/rudder-integration-clevertap-react-native/project.json
libs/rudder-integration-firebase-react-native/project.json
libs/rudder-integration-moengage-react-native/project.json
libs/rudder-integration-singular-react-native/project.json
libs/sdk/project.json

fix: add option to automatically detect dependencies

---

.github/workflows/draft-new-release.yml
scripts/generate-last-release-changelog.sh
scripts/sync-tags-in-nx-projects.sh

ci: fix cicid pipeline

---

apps/example/ios/Podfile.lock
libs/sdk/RNRudderSdk.podspec
package-lock.json

> bumped the version of native ios sdk to atleast 1.13.0

feat: bumped the version of native ios sdk to atleast 1.13.0

---

.nxignore
CODEOWNERS
apps/example/CHANGELOG.md
apps/example/ios/Podfile
apps/example/ios/Podfile.lock
apps/example/package.json
libs/rudder-integration-firebase-react-native/CHANGELOG.md
libs/rudder-integration-firebase-react-native/CHANGELOG_LATEST.md
libs/rudder-integration-firebase-react-native/android/build.gradle
libs/rudder-integration-firebase-react-native/package.json
libs/rudder-integration-firebase-react-native/project.json
libs/rudder-integration-firebase-react-native/rudder-integration-firebase-react-native.podspec
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.8.0 into master

---

.github/workflows/deploy-npm.yml
.github/workflows/publish-new-release.yml
apps/example/ios/Podfile.lock
apps/example/jest.config.ts
libs/rudder-integration-amplitude-react-native/jest.config.ts
libs/rudder-integration-appcenter-react-native/jest.config.ts
libs/rudder-integration-appsflyer-react-native/jest.config.ts
libs/rudder-integration-braze-react-native/jest.config.ts
libs/rudder-integration-clevertap-react-native/jest.config.ts
libs/rudder-integration-firebase-react-native/jest.config.ts
libs/rudder-integration-moengage-react-native/jest.config.ts
libs/rudder-integration-singular-react-native/jest.config.ts
libs/sdk/jest.config.ts
package-lock.json

ci(rudder-sdk-react-native-monorepo): improve slack notify and publish new release

---

libs/rudder-integration-amplitude-react-native/android/build.gradle
libs/rudder-integration-appcenter-react-native/android/build.gradle
libs/rudder-integration-appsflyer-react-native/android/build.gradle
libs/rudder-integration-braze-react-native/android/build.gradle
libs/rudder-integration-clevertap-react-native/android/build.gradle
libs/rudder-integration-firebase-react-native/android/build.gradle
libs/rudder-integration-moengage-react-native/android/build.gradle
libs/rudder-integration-singular-react-native/android/build.gradle
libs/sdk/android/build.gradle
libs/sdk/src/Constants.ts
package-lock.json
package.json

> Bumped Rudder Android SDK version in all packages to make it compatible with the latest Android SDK releases, up to v2.0.0.
> Fix [#1]()

fix: update rudder android sdk version in all packages upto 2.0

---

CONTRIBUTING.md

chore(rudder-sdk-react-native-monorepo): add contributing.md file

---

apps/example/ios/Example.xcodeproj/project.pbxproj
apps/example/ios/Podfile.lock
libs/rudder-integration-amplitude-react-native/android/src/main/java/com/rudderstack/integration/reactnative/amplitude/RudderIntegrationAmplitudeReactNativeModule.java
libs/rudder-integration-amplitude-react-native/ios/RudderIntegrationAmplitudeReactNative.m
libs/rudder-integration-appcenter-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appcenter/RudderIntegrationAppcenterReactNativeModule.java
libs/rudder-integration-appcenter-react-native/ios/RudderIntegrationAppcenterReactNative.m
libs/rudder-integration-appsflyer-react-native/android/src/main/java/com/rudderstack/integration/reactnative/appsflyer/RudderIntegrationAppsflyerReactNativeModule.java
libs/rudder-integration-appsflyer-react-native/ios/RudderIntegrationAppsflyerReactNative.m
libs/rudder-integration-braze-react-native/android/src/main/java/com/rudderstack/integration/reactnative/braze/RudderIntegrationBrazeReactNativeModule.java
libs/rudder-integration-braze-react-native/ios/RudderIntegrationBrazeReactNative.m
libs/rudder-integration-clevertap-react-native/android/src/main/java/com/rudderstack/integration/reactnative/clevertap/RudderIntegrationCleverTapReactNativeModule.java
libs/rudder-integration-clevertap-react-native/ios/RudderIntegrationCleverTapReactNative.m
libs/rudder-integration-firebase-react-native/android/src/main/java/com/rudderstack/integration/reactnative/firebase/RudderIntegrationFirebaseReactNativeModule.java
libs/rudder-integration-firebase-react-native/ios/RudderIntegrationFirebaseReactNative.m
libs/rudder-integration-moengage-react-native/android/src/main/java/com/rudderstack/integration/reactnative/moengage/RudderIntegrationMoengageReactNativeModule.java
libs/rudder-integration-moengage-react-native/ios/RudderIntegrationMoengageReactNative.m
libs/rudder-integration-singular-react-native/android/src/main/java/com/rudderstack/integration/reactnative/singular/RudderIntegrationSingularReactNativeModule.java
libs/rudder-integration-singular-react-native/ios/RudderIntegrationSingularReactNative.m
package-lock.json

- Fix module sync issue in integration package
> Fix [#1]()

fix: module sync issue in integration packages

---

apps/example/CHANGELOG.md
apps/example/ios/Podfile.lock
apps/example/package.json
libs/sdk/CHANGELOG.md
libs/sdk/CHANGELOG_LATEST.md
libs/sdk/ios/RNParamsConfigurator.h
libs/sdk/ios/RNRudderSdkModule.m
libs/sdk/ios/RNUserSessionPlugin.h
libs/sdk/package.json
libs/sdk/project.json
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.12.0 into master

---

apps/example/android/build.gradle
apps/example/ios/Example.xcodeproj/project.pbxproj
apps/example/ios/Podfile.lock
apps/example/package-lock.json
libs/rudder-integration-braze-react-native/android/build.gradle
libs/rudder-integration-braze-react-native/android/common_task.gradle
libs/rudder-integration-braze-react-native/rudder-integration-braze-react-native.podspec
package-lock.json

- Update the (iOS) Rudder-Braze minimum version to `1.3`.
- Update the (Android) [Rudder-Braze](com.rudderstack.android.integration:braze) minimum version to `1.3.0`.
> Fix [#1]()

feat: update native rudder braze sdks version

---

apps/example/CHANGELOG.md
apps/example/android/build.gradle
apps/example/ios/Example.xcodeproj/project.pbxproj
apps/example/ios/Podfile.lock
apps/example/package-lock.json
apps/example/package.json
libs/rudder-integration-braze-react-native/CHANGELOG.md
libs/rudder-integration-braze-react-native/CHANGELOG_LATEST.md
libs/rudder-integration-braze-react-native/android/build.gradle
libs/rudder-integration-braze-react-native/android/common_task.gradle
libs/rudder-integration-braze-react-native/package.json
libs/rudder-integration-braze-react-native/project.json
libs/rudder-integration-braze-react-native/rudder-integration-braze-react-native.podspec
package-lock.json
package.json
sonar-project.properties

chore(release): pulling release/2.14.0 into master

---

libs/rudder-integration-amplitude-react-native/project.json
libs/rudder-integration-appcenter-react-native/project.json
libs/rudder-integration-appsflyer-react-native/project.json
libs/rudder-integration-braze-react-native/project.json
libs/rudder-integration-clevertap-react-native/project.json
libs/rudder-integration-firebase-react-native/project.json
libs/rudder-integration-moengage-react-native/project.json
libs/rudder-integration-singular-react-native/project.json
libs/sdk/project.json

chore: fix interpolation issue

---

scripts/generate-last-release-changelog.sh
scripts/sync-tags-in-nx-projects.sh

> Correct the path of the DBEncryption plugin.
> Fix [#1]()

chore: correct the path of the plugin

---

package-lock.json
package.json

> override @babel/traverse to v7.23.2
> Fix [#1]()

chore(rudder-sdk-react-native-monorepo): fix snyk issue

---

CODEOWNERS

> Update Codeowners
> Fix [#1]()

chore(rudder-sdk-react-native-monorepo): update codeowners

---

.github/workflows/draft-new-release.yml
scripts/update-rn-sdk-version-in-constants-file.sh

> This will update the React Native SDK version in the Constants file. (From now on, we no longer need to manually maintain the version in the constants file.)
> Fix [#1]()

ci: update sdk version constants file

---

.github/workflows/update-minimum-android-and-ios-sdk.yml
package-lock.json

- Added a GitHub Action to update the minimum version of the Android and/or iOS SDKs.
- Added a sample picture to demonstrate the working of this action:
> Fix [#1]()

ci: add github action to update the android and ios sdks minimum version

---

.github/workflows/check-compatibility-of-native-sdks.yml

- This action provides a way to ensure that either the latest or beta/snapshot version of the native Android and iOS SDKs are compatible with the React Native SDKs and integrations.
- This action basically runs build check for Android, iOS (for iOS it also check for dynamic and static linking).
> Fix [#1]()

ci: add action to check the compatbility of the native android and ios sdks

---

.github/workflows/draft-new-release.yml

ci: update package-lock.json file when creating release branch

---

libs/sdk/RNRudderSdk.podspec

- Added support for the `tvOS` for our React Native iOS SDK.
> Fix [#1]()

feat: provide tvOS support for the react native iOS sdk

---

.github/workflows/deploy-npm.yml

chore(ci): build rn core sdk before publishing

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/draft-new-release.yml
.github/workflows/publish-new-release.yml
.github/workflows/update-minimum-android-and-ios-sdk.yml
CODEOWNERS

ci: update codeowner

---

libs/plugins/rudder-plugin-db-encryption-react-native/src/dbEncryptionPlugin.ts

[Linear ticket](https://linear.app/rudderstack/issue/SDK-1755/provide-putcustomcontext-api-support-on-the-react-native-sdk)
> Added a dummy commit (with no actual change). Which is required for changelog generation.
NOTE: There is a known issue with NX where, if we make a change in the RN core SDK, the DBEncryption plugin also gets affected, which in turn impacts the release pipeline.
> Fix [#1]()

feat: add dummy commit to trigger changelog generation

---

package-lock.json
package.json

> To address the snyk issues: We have updated the `braces` and `micromatch` to the latest version.
> Fix [#1]()

chore: override braces and micromatch depenedncies

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/draft-new-release.yml
.github/workflows/publish-new-release.yml
.github/workflows/update-minimum-android-and-ios-sdk.yml
CODEOWNERS

> Updated `CODEOWNERS`, `pr_reviewer` and `assignees` to `@rudderlabs/sdk-rn`
> Fix [#1]()

chore: update CODEOWNERS, pr_reviewer and assignees

---

apps/example/package-lock.json
apps/example/src/app/RudderEvents.tsx
libs/sdk/src/RudderClient.ts

I've fixed the declarations and implementation of the `alias` API.
- Marked `alias(previousId, newId)` as deprecated.
- Added the correct function declaration `alias(newId, [options])` to the API.
- The API was also fixed to return the promise from the bridge.
- We have to do this for all the other APIs as well later.
Misc:
- Updated the sample app with all the correct usages of the `alias` API.
- Also, added the missing `package-lock.json` file.
> Fix [#1]()

fix: alias api

---

.github/workflows/build-ios-checks.yml
apps/example/ios/Podfile.lock
package-lock.json
package.json

- Override the `cross-spawn` to `v7.0.6` to address the snyk vulnerability.
- Update the Axios override version to the latest version.
- GitHub action: Update the cocoapod version for iOS build check.
> Fix [#1]()

chore: address snyk vulnerability issue

---

apps/example/package-lock.json
apps/example/package.json

- Added override for `cross-spawn` to address snyk vulnerability.
> Fix [#1]()

chore(sample-app): address snyk vulnerability

---

.github/workflows/build-and-quality-checks.yml
.github/workflows/build-android-checks.yml
.github/workflows/build-ios-checks.yml
.github/workflows/check-compatibility-of-native-sdks.yml
.github/workflows/deploy-npm.yml
.github/workflows/draft-new-release.yml
.github/workflows/housekeeping.yaml
.github/workflows/notion-pr-sync.yml
.github/workflows/publish-new-release.yml
.github/workflows/test.yml

Added the following SHA's:
- ruby/setup-ruby with ruby/setup-ruby@28233a011b6bb8633ea908d76c6d23aab6518b5c #v1.233.0. Refer [here](https://github.com/ruby/setup-ruby/commit/28233a011b6bb8633ea908d76c6d23aab6518b5c).
- maxim-lobanov/setup-cocoapods@v1 with maxim-lobanov/setup-cocoapods@8e97e1e98e6ccf42564fdf5622c8feec74199377 #v1. Refer [here](https://github.com/maxim-lobanov/setup-cocoapods/commit/8e97e1e98e6ccf42564fdf5622c8feec74199377).
- maxim-lobanov/setup-xcode@v1 with maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd #v1. Refer [here](https://github.com/maxim-lobanov/setup-xcode/commit/60606e260d2fc5762a71e64e74b2174e8ea3c8bd).
- slackapi/slack-github-action@v2.0.0 with slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d  #v2.0.0. Refer …

ci: use shas for external github actions

---

.github/workflows/test.yml

- Removed deprecated `SonarSource/sonarcloud-github-action`.
- Added `SonarSource/sonarqube-scan-action@aa494459d7c39c106cc77b166de8b4250a32bb97  #v5.1.0`.
> Fix [#1]()

ci: update SonarQube scan action to use the latest v5.1.0
